<?php
session_start();

if (!isset($_SESSION['staff_id'])) {
    header('Location: staff_login.php');
    exit;
}

header('Cache-Control: no-store');
header('X-Content-Type-Options: nosniff');

function e($value): string
{
    return htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

$_SESSION['staff_csrf'] ??= bin2hex(random_bytes(32));
$error = '';
$flash = $_SESSION['quote_details_flash'] ?? '';
unset($_SESSION['quote_details_flash']);
$request = null;
$notes = [];
$submittedAt = null;

// Accept only the numeric quote identifier generated by the dashboard.
$id = $_GET['id'] ?? null;
if (!is_string($id) || !ctype_digit($id) || strlen($id) > 18 || (int) $id < 1) {
    http_response_code(400);
    exit('Invalid quote request.');
}

try {
    $config = require __DIR__ . '/config.local.php';
    $pdo = new PDO(
        $config['dsn'],
        $config['username'],
        $config['password'],
        [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false
        ]
    );

    // Recheck the active staff account, rather than trusting a saved username.
    $staffStmt = $pdo->prepare('SELECT username FROM staff_users WHERE id = :id LIMIT 1');
    $staffStmt->execute([':id' => $_SESSION['staff_id']]);
    $staff = $staffStmt->fetch();
    if (!$staff) {
        session_unset();
        session_destroy();
        header('Location: staff_login.php');
        exit;
    }

    // The existing dashboard already supports different primary-key column names.
    $columns = $pdo->query('SHOW COLUMNS FROM quote_requests')->fetchAll();
    $primaryKeys = [];
    $columnNames = [];
    foreach ($columns as $column) {
        $columnNames[] = $column['Field'];
        if ($column['Key'] === 'PRI') {
            $primaryKeys[] = $column;
        }
    }
    if (count($primaryKeys) !== 1 ||
        !preg_match('/^(?:tinyint|smallint|mediumint|int|bigint)\b/i', $primaryKeys[0]['Type'])) {
        throw new RuntimeException('The quote table must have a single numeric primary key.');
    }
    $primaryKeySql = '`' . str_replace('`', '``', $primaryKeys[0]['Field']) . '`';

    $quoteStmt = $pdo->prepare("SELECT * FROM quote_requests WHERE $primaryKeySql = :id LIMIT 1");
    $quoteStmt->execute([':id' => $id]);
    $request = $quoteStmt->fetch();
    if (!$request) {
        http_response_code(404);
        $error = 'Quote request not found.';
    } else {
        if (in_array('created_at', $columnNames, true)) {
            $submittedAt = $request['created_at'];
        } elseif (in_array('submitted_at', $columnNames, true)) {
            $submittedAt = $request['submitted_at'];
        }

        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            if (!hash_equals($_SESSION['staff_csrf'], (string) ($_POST['csrf'] ?? ''))) {
                http_response_code(403);
                exit('Invalid request. Reload the page and try again.');
            }

            $note = $_POST['note'] ?? null;
            if (!is_string($note) || trim($note) === '') {
                $error = 'Please enter a note.';
            } elseif (strlen($note) > 8000 ||
                (function_exists('mb_strlen') ? mb_strlen($note, 'UTF-8') : strlen($note)) > 2000) {
                $error = 'Notes must be 2,000 characters or fewer.';
            } else {
                $insert = $pdo->prepare(
                    'INSERT INTO quote_staff_notes (quote_id, staff_username, note)
                     VALUES (:quote_id, :staff_username, :note)'
                );
                $insert->execute([
                    ':quote_id' => $id,
                    ':staff_username' => $staff['username'],
                    ':note' => trim($note)
                ]);
                $_SESSION['quote_details_flash'] = 'Internal note saved.';
                header('Location: quote_details.php?id=' . rawurlencode($id), true, 303);
                exit;
            }
        }

        $notesStmt = $pdo->prepare(
            'SELECT staff_username, note, created_at
             FROM quote_staff_notes
             WHERE quote_id = :quote_id
             ORDER BY created_at DESC, id DESC LIMIT 100'
        );
        $notesStmt->execute([':quote_id' => $id]);
        $notes = $notesStmt->fetchAll();
    }
} catch (Throwable $exception) {
    error_log($exception->getMessage());
    $error = 'Unable to load or save this request. Make sure the staff-notes SQL has been run.';
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Quote Details | ABC Plumbing</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background: #f4f8fa; color: #18323e; }
        .brand-abc { color: #167d91; font-weight: 800; font-size: 1.7rem; line-height: 1; }
        .brand-subtitle { color: #18323e; font-size: .68rem; font-weight: 700; letter-spacing: .09em; }
        .btn-brand { background: #167d91; border-color: #167d91; color: white; }
        .btn-brand:hover, .btn-brand:focus { background: #0e5968; border-color: #0e5968; color: white; }
        .request-message, .note-text { white-space: pre-wrap; overflow-wrap: anywhere; }
        .detail-label { color: #5b6e78; font-size: .85rem; margin-bottom: .2rem; }
    </style>
</head>
<body>
<main class="container py-4">
    <header class="d-flex flex-wrap justify-content-between align-items-center gap-3 border-bottom pb-3 mb-4">
        <a href="index.html" class="text-decoration-none d-flex flex-column" aria-label="ABC Plumbing home">
            <span class="brand-abc">ABC</span>
            <span class="brand-subtitle">PLUMBING SERVICES</span>
        </a>
        <a href="staff_dashboard.php" class="btn btn-outline-secondary rounded-pill px-4">← Back to dashboard</a>
    </header>

    <h1 class="h2 fw-bold mb-3">Quote details</h1>
    <?php if ($flash): ?>
        <div class="alert alert-success" role="status"><?= e($flash) ?></div>
    <?php endif; ?>
    <?php if ($error): ?>
        <div class="alert alert-danger" role="alert"><?= e($error) ?></div>
    <?php endif; ?>

    <?php if ($request): ?>
        <section class="bg-white border rounded-4 p-4 mb-4" aria-labelledby="requestHeading">
            <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3">
                <h2 id="requestHeading" class="h4 mb-0">Request #<?= e($id) ?></h2>
                <span class="badge text-bg-info fs-6"><?= e($request['status'] ?? 'New') ?></span>
            </div>
            <div class="row g-3">
                <div class="col-sm-6"><div class="detail-label">Customer</div><div class="fw-semibold"><?= e($request['customer_name'] ?? '') ?></div></div>
                <div class="col-sm-6"><div class="detail-label">Service</div><div class="fw-semibold"><?= e($request['service'] ?? '') ?></div></div>
                <div class="col-sm-6"><div class="detail-label">Email</div><div><?= e($request['email'] ?? '') ?></div></div>
                <div class="col-sm-6"><div class="detail-label">Phone</div><div><?= e($request['phone'] ?? '') ?></div></div>
                <div class="col-sm-6"><div class="detail-label">Postcode</div><div><?= e($request['postcode'] ?? '') ?></div></div>
                <div class="col-sm-6"><div class="detail-label">Preferred contact</div><div><?= e($request['contact_method'] ?? '') ?></div></div>
                <div class="col-12"><div class="detail-label">Submitted</div><div><?= $submittedAt !== null ? e($submittedAt) : 'Date not recorded in the current quote table.' ?></div></div>
                <div class="col-12">
                    <div class="detail-label">Customer message</div>
                    <div class="request-message border rounded-3 bg-light p-3"><?= e($request['message'] ?? '') ?></div>
                </div>
            </div>
        </section>

        <section class="bg-white border rounded-4 p-4 mb-4" aria-labelledby="notesHeading">
            <h2 id="notesHeading" class="h4 mb-2">Internal staff notes</h2>
            <p class="text-muted">Notes are visible only to signed-in staff. They are not sent to the customer.</p>
            <form method="post" action="quote_details.php?id=<?= e($id) ?>">
                <input type="hidden" name="csrf" value="<?= e($_SESSION['staff_csrf']) ?>">
                <label for="note" class="form-label fw-semibold">Add a note</label>
                <textarea id="note" name="note" class="form-control mb-3" rows="4" maxlength="2000" required placeholder="e.g. Called customer; waiting for availability."><?= e(is_string($_POST['note'] ?? null) && $error ? $_POST['note'] : '') ?></textarea>
                <button type="submit" class="btn btn-brand fw-semibold px-4">Save note</button>
            </form>
            <hr class="my-4">
            <h3 class="h5 mb-3">Note history</h3>
            <?php if (!$notes): ?>
                <p class="text-muted mb-0">No internal notes yet.</p>
            <?php else: ?>
                <?php foreach ($notes as $noteItem): ?>
                    <article class="border rounded-3 p-3 mb-3">
                        <div class="d-flex flex-wrap justify-content-between gap-2 mb-2 small text-muted">
                            <span class="fw-semibold"><?= e($noteItem['staff_username']) ?></span>
                            <time><?= e($noteItem['created_at']) ?></time>
                        </div>
                        <div class="note-text"><?= e($noteItem['note']) ?></div>
                    </article>
                <?php endforeach; ?>
            <?php endif; ?>
        </section>
    <?php endif; ?>
</main>
</body>
</html>
